# Generated by Django 5.0.3 on 2024-03-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountmultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensajem', models.CharField(blank=True, max_length=255)),
                ('exel', models.FileField(upload_to='documents/')),
                ('imagenm', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
