# Generated by Django 5.0.4 on 2024-04-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_accountmultiple_exel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmultiple',
            name='mensajem',
            field=models.CharField(max_length=255),
        ),
    ]
